apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name  }}-pv
  labels:
    name: {{ .Release.Name  }}-pv
spec:
  nfs:
    path: /data/volumes/v1/spring-boot
    server: master01
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name  }}-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi