apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  labels:
    {{- include "spring-boot-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30010
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spring-boot-chart.selectorLabels" . | nindent 4 }}